# Проверочное задание

# 🏃‍♂️🤸‍♂️🏋️‍♀️ 
Сегодня вы аналитики популярной сети фитнес-клубов, которая предлагает три вида тренировок для взрослых и детей:
- Обычное занятие в зале,
- Сайклинг (кардиотренировка на велотренажёре),
- Функциональная тренировка.

Первая тренировка в наших клубах всегда бесплатная.

Доступна следующая выгрузка данных:
- О наших клиентах — `users.xlsx`,

- Об оплатах тренировок — `payments.xlsx`,

- О посещении тренировок — `workouts.csv`. 

Директор  сети и попросил ответить на вопросы, которые позволят более точно сформулировать планы на следующий год:

1. Как изменялась ежемесячная выручка по каждому типу тренировок в течение 2020 года?
2. Какие тренеры в сети провели больше всего платных занятий за все время?
3. Сколько денег и за какие типы тренировок принесли клиенты, которые начали заниматься в ноябре?
4. Какие регионы приносят нашей сети больше всего и меньше всего выручки? Результаты регионов будут обсуждаться на совете директоров, поэтому необходимо выгрузить этот отчет в файл формата Excel, чтобы включить его в раздаточный материал для совещания.

Выполнив следующие четыре задания, вы сможете последовательно ответить на все вопросы руководителя. Для начала убедитесь, что три новых файла с данными скачаны в папку с этим ноутбуком, импортируй нужные библиотеки и загрузи данные в датафреймы.

In [3]:
!pip install pandas

Requirement already satisfied: pandas in /home/jezvgg/Projects/infa/.venv/lib/python3.10/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in /home/jezvgg/Projects/infa/.venv/lib/python3.10/site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/jezvgg/Projects/infa/.venv/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/jezvgg/Projects/infa/.venv/lib/python3.10/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/jezvgg/Projects/infa/.venv/lib/python3.10/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /home/jezvgg/Projects/infa/.venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]1/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [5]:
import pandas as pd
from datetime import datetime

users = pd.read_excel("users.xlsx") # загружаем данные по клиентам
payments = pd.read_excel("payments.xlsx") # загружаем данные по платежам
workouts = pd.read_csv("workouts.csv") # загружаем данные по тренировкам

pd.set_option('display.float_format', lambda x: '%.2f' % x) # эта строка поможет удобно выводить большие числа в этом ноутбуке

## Задание 1

Подготовь данные для ответа на вопрос: «__Как изменялась ежемесячная выручка по каждому типу тренировок в течение 2020 года?__». 

### Как это сделать?

1. Изучи датафрейм `payments` и для начала переведи даты в формат `datetime`.

2. С помощью фильтрации датафрейма выбери платежи только за 2020 год.

3. Обрати внимание, что платежи хранятся в разных валютах — для удобства приведем все к рублям. Сначала добавь в датафрейм столбец `fx_rate` с курсом валюты и заполни его с помощью метода `apply()`: если это USD, то берем значение переменной `USD_RATE`, если RUR — ставим значение `1`. Предварительно нужно определить функцию, которая реализует эту несложную логику.

4. Добавь еще один столбец `amount_rub` с суммой платежа в рублях. Для этого умножь столбец с суммой платежа на столбец `fx_rate` с курсом валют.

5. Получи датафрейм с разбивкой выручки по месяцам и по типам тренировок с помощью группировки с суммой методом `groupby()`. 

6. Выведи результат на экран.

🤔 *Предположи, основываясь на проделанном анализе.* Благодаря каким тренировкам компания могла получать больше выручки? У этого задания нет правильного ответа,  предлагается некое размышление.

In [8]:
print(workouts.columns.to_list)

<bound method IndexOpsMixin.tolist of Index(['workout_id', 'cost', 'start_at', 'status', 'workout_schedule_type',
       'client_id', 'client_status', 'workout_type', 'trainer_department',
       'trainer_id', 'currency'],
      dtype='object')>

In [9]:
payments['payment_date'] = pd.to_datetime(payments['payment_date'], dayfirst=True)

In [12]:
USD_RATE = 73.14 # курс доллара

def map_currency(currency): # определи функцию для заполнения столбца fx_rate методом .apply()
 if currency == "USD":
    return USD_RATE
 else:
    return 1
    

payments_2020 = payments[payments['payment_date'].dt.year == 2020].copy()

payments_2020['fx_rate'] = payments_2020['currency'].apply(map_currency)
print(payments_2020)

       user_id  payment_id workout_type  amount payment_date currency  fx_rate
9435   2083165     2138681      general 8358.33   2020-01-30      RUR     1.00
9436   1807292     2138712      general 8163.60   2020-08-18      RUR     1.00
9437   3187806     2138734      general 8801.06   2020-10-12      RUR     1.00
9438   1807292     2138805      general 7522.49   2020-08-20      RUR     1.00
9439   1807690     2138846      general 8056.33   2020-05-22      RUR     1.00
...        ...         ...          ...     ...          ...      ...      ...
20790  3301629     2931094      general 8358.33   2020-05-12      RUR     1.00
20791  4294927     2931391      general 8477.52   2020-10-07      RUR     1.00
20792  2181319     2931540      general 9409.41   2020-03-22      RUR     1.00
20793  5505898  1000012868      general 8918.91   2020-03-02      RUR     1.00
20794  2915674  1000022868      general 8103.84   2020-06-06      RUR     1.00

[11360 rows x 7 columns]

In [13]:
payments_2020['amount_rub'] = payments_2020['amount'] * payments_2020['fx_rate']
payments_2020.head()

,user_id,payment_id,workout_type,amount,payment_date,currency,fx_rate,amount_rub
9435,2083165,2138681,general,8358.33,2020-01-30,RUR,1.00,8358.33
9436,1807292,2138712,general,8163.60,2020-08-18,RUR,1.00,8163.60
9437,3187806,2138734,general,8801.06,2020-10-12,RUR,1.00,8801.06
9438,1807292,2138805,general,7522.49,2020-08-20,RUR,1.00,7522.49
9439,1807690,2138846,general,8056.33,2020-05-22,RUR,1.00,8056.33

In [14]:
payments_2020['payment_month'] = payments_2020['payment_date'].dt.month
revenue_month = payments_2020.groupby(['payment_month', 'workout_type'])['amount_rub'].sum().reset_index()
print(revenue_month)

    payment_month     workout_type  amount_rub
0               1          cycling    37611.51
1               1  functional test     8000.52
2               1          general  9231431.45
3               2          cycling    63026.64
4               2  functional test     7020.81
5               2          general 15056524.85
6               3          cycling    49843.52
7               3  functional test    17098.39
8               3          general 19517875.66
9               4          cycling  1006056.79
10              4  functional test     7015.99
11              4          general 25308002.27
12              5          cycling   103156.30
13              5  functional test     9050.01
14              5          general 27269168.04
15              6          cycling    55233.26
16              6  functional test     7020.81
17              6          general 19536194.78
18              7          cycling   119472.93
19              7  functional test     7800.90
20              7          general 21212408.89
21              8          cycling    84327.61
22              8  functional test     7110.81
23              8          general 22034979.24
24              9          cycling   752520.72
25              9  functional test    23597.35
26              9          general 23959753.45
27             10          cycling   886795.92
28             10  functional test    28857.61
29             10          general 24389609.10
30             11          cycling   184408.30
31             11          general 24875912.84
32             12          cycling    38017.44
33             12          general  7924395.25

## Задание 2

Определи, __какой тренер в сети провел больше всего платных занятий за все время__. С самыми эффективными сотрудниками мы организуем интервью, чтобы понять, что влияет на их результат.

### Как это сделать? 

1. Изучи датафрейм `workouts`.

2. Исключи из датафрейма тренеров из департамента `Sales`, так как они проводят только бесплатные тренировки, а нам интересны только платные занятия.

3. Сделай группировку по `trainer_id` и выведи количество уникальных тренировок по `workout_id`. 

4. Найди максимальное количество тренировок и сохрани его в переменную `max_trainings`. Не забудь, что после группировки в прошлом пункте, индексом стал столбец `trainer_id`. Возможно, тебе понадобится метод, который возвращает индексы в колонки.

5. Выведи на экран id тренера, у которого количество тренировок равно значению `max_trainings`.

In [17]:
work = workouts.copy()
print(work.head())

   workout_id   cost          start_at   status workout_schedule_type  \
0    30793909    NaN  2020-11-13 12:45  success                 trial
1    31123309 750.00  2020-11-21 13:00  success               regular
2    31412167 750.00  2020-11-28 13:00  success               regular
3    31703605 750.00  2020-12-05 13:00  success               regular
4    26904500    NaN  2020-08-06 18:20  success                 trial

   client_id client_status workout_type trainer_department  trainer_id  \
0      22034           NaN      general              Sales    10722051
1      22034           new      general          Spartacus      940642
2      22034           new      general          Spartacus      940642
3      22034        active      general          Spartacus      940642
4      88101           NaN      general              Sales     3826530

  currency
0      RUR
1      RUR
2      RUR
3      RUR
4      RUR

In [18]:
pw = work[(work['trainer_department'] != 'Sales')].copy()
print(pw.head())

   workout_id   cost          start_at   status workout_schedule_type  \
1    31123309 750.00  2020-11-21 13:00  success               regular
2    31412167 750.00  2020-11-28 13:00  success               regular
3    31703605 750.00  2020-12-05 13:00  success               regular
5    27205345 750.00  2020-08-15 10:00  success                single
6    27439942 750.00  2020-08-20 19:00  success               regular

   client_id client_status workout_type trainer_department  trainer_id  \
1      22034           new      general          Spartacus      940642
2      22034           new      general          Spartacus      940642
3      22034        active      general          Spartacus      940642
5      88101           new      general         Consultant    10231664
6      88101           new      general         Consultant    10231664

  currency
1      RUR
2      RUR
3      RUR
5      RUR
6      RUR

In [19]:
trainer = pw.groupby('trainer_id')['workout_id'].nunique()
trainer.head()

trainer_id
1308      1
1994    187
2556      4
3249      4
3526      1
Name: workout_id, dtype: int64

In [20]:
max_train = trainer.max()
print(max_train)

311

In [21]:

best_trainer = trainer[trainer == max_train]
print(best_trainer)

trainer_id
7010157    311
Name: workout_id, dtype: int64

## Задание 3

Посчитайте, __сколько денег и за какие типы тренировок принесли клиенты, которые начали заниматься в ноябре__.  

### Как это сделать?

1. Изучи датафрейм `users` и переведи даты в формат `datetime`.
2. Отбери только тех клиентов, кто начал заниматься с 1 по 30 ноября 2020 года, код уже готов, обрати внимание, как можно передать сразу 2 условия в `loc[]`
3. Объедини получившийся набор данных с платежами из датафрейма `payments` по `user_id`.

4. Сгруппируй результат по `workout_type` и найди сумму по `amount_rub`.

In [23]:
# Сначала преобразуем столбец в datetime
users['free_workout_datetime'] = pd.to_datetime(users['free_workout_datetime'])

# Затем фильтруем
november_users = users.loc[(users['free_workout_datetime'] >= datetime(2020, 11, 1)) &
                           (users['free_workout_datetime'] < datetime(2020, 12, 1))]

print(november_users)

     first_contact_datetime   age free_workout_datetime  \
11      2018-03-04 14:05:25 12.00   2020-11-16 18:20:00
24      2018-11-08 15:26:25 10.00   2020-11-20 17:00:00
41      2020-11-06 21:55:59 21.00   2020-11-16 18:15:00
89      2018-03-01 10:57:57   NaN   2020-11-10 18:45:00
95      2020-11-08 23:55:18   NaN   2020-11-10 13:15:00
...                     ...   ...                   ...
4224    2020-11-18 18:28:27   NaN   2020-11-25 10:15:00
4244    2018-11-10 11:41:53  8.00   2020-11-22 19:00:00
4251    2017-01-27 19:47:00   NaN   2020-11-26 13:15:00
4257    2020-03-18 17:36:21   NaN   2020-11-02 14:20:00
4263    2016-08-31 10:22:36   NaN   2020-11-04 13:45:00

     first_payment_datetime  workouts_successful  workouts_total  \
11      2020-11-18 10:29:44                    5               5
24      2020-11-20 17:35:57                    5               5
41      2020-11-16 18:46:29                    6               6
89      2020-11-10 19:13:39                    8               8
95      2020-11-10 13:37:41                   12              13
...                     ...                  ...             ...
4224    2020-11-25 10:41:20                    2               4
4244    2020-11-22 19:57:55                    2               2
4251    2020-11-27 17:33:25                    1               1
4257    2020-11-02 14:54:20                    8               8
4263    2020-11-04 14:10:02                    4               8

      months_active  user_id                       region   geo_group
11                2  1398709  Москва и Московская область      Москва
24                2  2975028  Москва и Московская область      Москва
41                2  2836636                          NaN         СНГ
89                2  1374881  Москва и Московская область      Москва
95                2  1081498  Москва и Московская область      Москва
...             ...      ...                          ...         ...
4224              2  2192945           Ростовская область  Регионы РФ
4244              2  2986349  Москва и Московская область      Москва
4251              1   195201  Москва и Московская область      Москва
4257              2  3228377  Москва и Московская область      Москва
4263              2    73173  Москва и Московская область      Москва

[236 rows x 10 columns]

In [25]:

november = november_users.merge(payments, on='user_id')
print(november)

    first_contact_datetime   age free_workout_datetime first_payment_datetime  \
0      2018-03-04 14:05:25 12.00   2020-11-16 18:20:00    2020-11-18 10:29:44
1      2018-11-08 15:26:25 10.00   2020-11-20 17:00:00    2020-11-20 17:35:57
2      2020-11-06 21:55:59 21.00   2020-11-16 18:15:00    2020-11-16 18:46:29
3      2018-03-01 10:57:57   NaN   2020-11-10 18:45:00    2020-11-10 19:13:39
4      2020-11-08 23:55:18   NaN   2020-11-10 13:15:00    2020-11-10 13:37:41
..                     ...   ...                   ...                    ...
255    2020-11-18 18:28:27   NaN   2020-11-25 10:15:00    2020-11-25 10:41:20
256    2018-11-10 11:41:53  8.00   2020-11-22 19:00:00    2020-11-22 19:57:55
257    2017-01-27 19:47:00   NaN   2020-11-26 13:15:00    2020-11-27 17:33:25
258    2020-03-18 17:36:21   NaN   2020-11-02 14:20:00    2020-11-02 14:54:20
259    2016-08-31 10:22:36   NaN   2020-11-04 13:45:00    2020-11-04 14:10:02

     workouts_successful  workouts_total  months_active  user_id  \
0                      5               5              2  1398709
1                      5               5              2  2975028
2                      6               6              2  2836636
3                      8               8              2  1374881
4                     12              13              2  1081498
..                   ...             ...            ...      ...
255                    2               4              2  2192945
256                    2               2              2  2986349
257                    1               1              1   195201
258                    8               8              2  3228377
259                    4               8              2    73173

                          region   geo_group  payment_id workout_type  \
0    Москва и Московская область      Москва     2817467      cycling
1    Москва и Московская область      Москва     2829176      general
2                            NaN         СНГ     2809454      general
3    Москва и Московская область      Москва     2781845      general
4    Москва и Московская область      Москва     2779460      general
..                           ...         ...         ...          ...
255           Ростовская область  Регионы РФ     2850060      general
256  Москва и Московская область      Москва     2837636      general
257  Москва и Московская область      Москва     2863760      general
258  Москва и Московская область      Москва     2743319      general
259  Москва и Московская область      Москва     2752575      general

      amount payment_date currency
0    8759.56   2020-06-13      RUR
1    9744.62   2020-09-10      RUR
2    9316.76   2020-07-24      RUR
3    9763.81   2020-11-08      RUR
4    9051.47   2020-09-09      RUR
..       ...          ...      ...
255  9316.76   2020-08-18      RUR
256  9409.41   2020-05-22      RUR
257 10310.10   2020-10-12      RUR
258  9970.29   2020-06-11      RUR
259  8258.33   2020-01-18      RUR

[260 rows x 15 columns]

In [26]:

november['fx_rate'] = november['currency'].apply(map_currency)
november['amount_rub'] = november['amount'] * november['fx_rate']
result = november.groupby('workout_type')['amount_rub'].sum()
result.head()

workout_type
cycling     77676.28
general   5636628.32
Name: amount_rub, dtype: float64

## Задание 4

Выясни, **какие регионы приносят нашей сети больше всего и меньше всего выручки**. 

### Как это сделать

1. Создай новый датафрейм `user_regions` из колонок `user_id` и `region` датафрейма `users`.

2. Создай новый датафрейм `user_payments` из колонок `user_id` и `amount_rub` датафрейма `payments`.
3. C помощью `.merge()` объедини датафреймы `user_regions` и `user_payments`
4. Обрати внимание, что у некоторых клиентов не заполнен регион. `dropna()` — хороший метод для очистки датасета от строк, в которых не хватает каких-то значений.
5. Сгруппируй данные о выручке по региону, а затем отсортируй их.
6. Выведи на экран топ-5 регионов с самой маленькой выручкой. 
7. Выведи на экран топ-5 регионов с самой большой выручкой. 
8. Сохрани отсортированный по убыванию список регионов с выручкой в файл `task_fitnes.xlsx` с помощью метода `to_excel()`.

🤔 *Предположи, основываясь на проделанном анализе.* Как сейчас распределялась
выручка между регионами? У этого задания нет правильного ответа, можно поразмышлять.

In [27]:
user_regions = users[["user_id", "region"]]
user_regions.head()

   user_id                       region
0  2790000                          NaN
1   780106                          NaN
2  1133376                          NaN
3  1996499                          NaN
4    57899  Москва и Московская область

# 🎉🎉🎉

In [29]:
payments['fx_rate'] = payments['currency'].apply(map_currency)
payments['amount_rub'] = payments['amount'] * payments['fx_rate']
payments_2020.head()

user_payments = payments[["user_id", "amount_rub"]]
user_payments.head()

   user_id  amount_rub
0   193433     7522.49
1   193433     8346.04
2   329226     8707.38
3   193433     7432.49
4   193433      114.64

In [30]:
jk = pd.merge(user_regions, user_payments).dropna(subset=["region"])
jk.head()

    user_id                       region  amount_rub
12    57899  Москва и Московская область     9051.47
13  4197252  Москва и Московская область     8748.69
14  4197252  Москва и Московская область     8951.47
15  4197252  Москва и Московская область     9051.47
16  4197252  Москва и Московская область     8358.33

In [31]:
sort_region = jk.groupby('region')['amount_rub'].sum().sort_values(ascending=False)
sort_region.head()

region
Москва и Московская область               121137445.26
Санкт-Петербург и Ленинградская область    26429453.52
Новосибирская область                       4968301.32
Краснодарский край                          4061682.64
Республика Татарстан                        3891956.28
Name: amount_rub, dtype: float64

In [32]:
top_min = sort_region.nsmallest(5)
top_min.head()

region
Магаданская область    8938.74
Республика Калмыкия    9277.15
Еврейская АО          19615.55
Луганская область     19703.92
Республика Алтай      20172.72
Name: amount_rub, dtype: float64

In [33]:
top_max = sort_region.nlargest(5)
top_max.head()

region
Москва и Московская область               121137445.26
Санкт-Петербург и Ленинградская область    26429453.52
Новосибирская область                       4968301.32
Краснодарский край                          4061682.64
Республика Татарстан                        3891956.28
Name: amount_rub, dtype: float64

In [34]:
top_min.to_excel("task_fitnes.xlsx")